# Multi-stage build: 436MB

FROM maven:3.9.6-eclipse-temurin-21 AS build

RUN mkdir /app
COPY . /app
WORKDIR /app
RUN mvn package

FROM eclipse-temurin:21

RUN mkdir /app
COPY --from=build /app /app
WORKDIR /app

ENTRYPOINT ["java", "-jar", "target/javadocker-0.1.jar"]
