# Using jlink on a minimal base: 115MB

FROM maven:3.9.6-eclipse-temurin-21 AS build

RUN mkdir /app
COPY . /app
WORKDIR /app
RUN mvn package \
 && jar xf target/javadocker-0.1.jar \
 && jdeps --ignore-missing-deps -q --recursive --multi-release 21 --print-module-deps target/javadocker-0.1.jar > deps.info \
 && jlink --add-modules "$(cat deps.info)" --strip-debug --compress zip-6 --no-header-files --no-man-pages --output /myjre

FROM debian:stable-slim

ENV JAVA_HOME /usr/java/jdk21
ENV PATH $JAVA_HOME/bin:$PATH
COPY --from=build /myjre $JAVA_HOME
RUN mkdir /app
COPY --from=build /app /app
WORKDIR /app

ENTRYPOINT ["java", "-jar", "target/javadocker-0.1.jar"]
