# GraalVM native image: 89MB

FROM ghcr.io/graalvm/native-image-community:25 AS build

RUN mkdir /opt/maven \
 && curl -fL https://repo1.maven.org/maven2/org/apache/maven/apache-maven/3.9.14/apache-maven-3.9.14-bin.tar.gz | tar xz -C /opt/maven --strip-components=1

ENV \
  PATH="/opt/maven/bin:${PATH}" \
  MAVEN_HOME=/opt/maven \
  M2_HOME=/opt/maven

COPY . /app
WORKDIR /app
RUN mvn package -Pgraal

FROM debian:stable-slim

COPY --from=build /app/target/javadocker /javadocker

ENTRYPOINT ["/javadocker"]
