# GraalVM native image FROM scratch: 16MB
# Note that we need to link in libc;
# we do this using the `--static` flag in the `graal-static` Maven profile

FROM ghcr.io/graalvm/graalvm-community:21 AS build

RUN mkdir /opt/maven \
 && curl -fL https://repo1.maven.org/maven2/org/apache/maven/apache-maven/3.9.6/apache-maven-3.9.6-bin.tar.gz | tar xz -C /opt/maven --strip-components=1

ENV \
  PATH="/opt/maven/bin:${PATH}" \
  MAVEN_HOME=/opt/maven \
  M2_HOME=/opt/maven

COPY . /app
WORKDIR /app
RUN mvn package -Pgraal-static

FROM scratch

COPY --from=build /app/target/javadocker /javadocker

ENTRYPOINT ["/javadocker"]
